name: data_operations_service
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.15.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  cloud_firestore: ^4.7.1
  aqueduct: ^3.3.0+1
  uuid: ^2.2.2
  login:
    git:
      url: https://github.com/KajcsaRenataGabriela/authentication_service.git

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true