// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKpxGXORx4fAbPnBwxGE9CLhGcJKmKtl4',
    appId: '1:690246310160:web:e0807f8770cb43d569ad95',
    messagingSenderId: '690246310160',
    projectId: 'what-s-in-my-fridge-app-e212d',
    authDomain: 'what-s-in-my-fridge-app-e212d.firebaseapp.com',
    storageBucket: 'what-s-in-my-fridge-app-e212d.appspot.com',
    measurementId: 'G-PHCJHB2YEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvDDdHuQkvYAn-1vxJlnK7U--SJRThOTw',
    appId: '1:690246310160:android:772a28d0364c2e6d69ad95',
    messagingSenderId: '690246310160',
    projectId: 'what-s-in-my-fridge-app-e212d',
    storageBucket: 'what-s-in-my-fridge-app-e212d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8r_Jmn24HXY9skYypvObQ5hSpRQ9jkHI',
    appId: '1:690246310160:ios:5bd2d593f38f16f369ad95',
    messagingSenderId: '690246310160',
    projectId: 'what-s-in-my-fridge-app-e212d',
    storageBucket: 'what-s-in-my-fridge-app-e212d.appspot.com',
    iosBundleId: 'com.example.dataOperationsService',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8r_Jmn24HXY9skYypvObQ5hSpRQ9jkHI',
    appId: '1:690246310160:ios:5bd2d593f38f16f369ad95',
    messagingSenderId: '690246310160',
    projectId: 'what-s-in-my-fridge-app-e212d',
    storageBucket: 'what-s-in-my-fridge-app-e212d.appspot.com',
    iosBundleId: 'com.example.dataOperationsService',
  );
}
